'use client';

import { useMemo, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Building2, CalendarDays, ChevronRight, CircleParking, GraduationCap, MapPin, Sparkles, Store, TrainFront, TreePine, TrendingUp, Zap } from 'lucide-react';
import { ChartContainer, ChartTooltip, ChartTooltipContent } from '@/components/ui/chart';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

const apartments = [
  { rank:1,name:'동탄역 롯데캐슬',dong:'오산동',count:28,sale:14.8,jeonse:7.4,rent:'5,000 / 260',change:'+4.2%' },
  { rank:2,name:'동탄역 시범한화 꿈에그린',dong:'청계동',count:24,sale:11.25,jeonse:6.1,rent:'5,000 / 210',change:'+2.8%' },
  { rank:3,name:'동탄2신도시 센트럴푸르지오',dong:'청계동',count:21,sale:9.6,jeonse:5.5,rent:'3,000 / 185',change:'+1.6%' },
  { rank:4,name:'동탄역 반도유보라 아이비파크',dong:'오산동',count:19,sale:10.75,jeonse:5.8,rent:'5,000 / 190',change:'+3.1%' },
  { rank:5,name:'동탄역 더샵 센트럴시티',dong:'청계동',count:17,sale:12.4,jeonse:6.8,rent:'7,000 / 220',change:'+2.2%' },
  { rank:6,name:'동탄역 유림노르웨이숲',dong:'오산동',count:16,sale:11.9,jeonse:6.4,rent:'5,000 / 230',change:'+1.9%' },
  { rank:7,name:'시범다은마을 포스코더샵',dong:'반송동',count:15,sale:8.65,jeonse:4.9,rent:'3,000 / 170',change:'+1.3%' },
  { rank:8,name:'동탄나루마을 월드메르디앙',dong:'반송동',count:13,sale:7.75,jeonse:4.5,rent:'3,000 / 155',change:'+0.8%' },
  { rank:9,name:'향남시범 살구꽃마을 풍림아이원',dong:'향남읍',count:12,sale:4.15,jeonse:2.8,rent:'2,000 / 95',change:'+0.6%' },
  { rank:10,name:'동탄센트럴자이',dong:'영천동',count:11,sale:8.95,jeonse:5.1,rent:'4,000 / 175',change:'+1.1%' },
];
const dongs = ['전체','오산동','청계동','반송동','영천동','향남읍'];
const volumeBase = [
  {day:'8/24',sale:31,jeonse:22,rent:14},{day:'8/25',sale:42,jeonse:28,rent:19},{day:'8/26',sale:36,jeonse:31,rent:17},{day:'8/27',sale:49,jeonse:26,rent:21},{day:'8/28',sale:46,jeonse:34,rent:23},{day:'8/29',sale:58,jeonse:39,rent:27},{day:'8/30',sale:52,jeonse:36,rent:24},
];
const trend = [
  {month:'3월',top:13.4,mine:8.5},{month:'4월',top:13.7,mine:8.6},{month:'5월',top:13.9,mine:8.7},{month:'6월',top:14.1,mine:8.8},{month:'7월',top:14.35,mine:8.85},{month:'8월',top:14.8,mine:8.95},
];
const locationItems = [
  {icon:Zap,label:'삼성전자 화성캠퍼스',distance:'5.4 km',note:'차량 약 13분',score:78,color:'text-amber-600 bg-amber-50'},
  {icon:TrainFront,label:'동탄역 (GTX-A·SRT)',distance:'620 m',note:'도보 약 9분 · 역세권',score:94,color:'text-blue-600 bg-blue-50'},
  {icon:GraduationCap,label:'동탄초·중 학군',distance:'480 m',note:'1km 내 학교 6곳',score:88,color:'text-violet-600 bg-violet-50'},
  {icon:TreePine,label:'여울공원',distance:'280 m',note:'도보 약 4분',score:92,color:'text-emerald-600 bg-emerald-50'},
  {icon:Store,label:'롯데백화점·중심상권',distance:'340 m',note:'생활편의시설 밀집',score:91,color:'text-rose-600 bg-rose-50'},
  {icon:CircleParking,label:'경부고속도로 진입',distance:'3.1 km',note:'차량 약 8분',score:83,color:'text-cyan-600 bg-cyan-50'},
];

const priceText = (deal:string,a:typeof apartments[number]) => deal==='매매'?`${a.sale}억`:deal==='전세'?`${a.jeonse}억`:a.rent;

export default function Home(){
  const [dong,setDong]=useState('전체'); const [apartment,setApartment]=useState('전체 아파트'); const [deal,setDeal]=useState('매매'); const [period,setPeriod]=useState('월간');
  const [start,setStart]=useState('2026-08-01'); const [end,setEnd]=useState('2026-08-30'); const [topChoice,setTopChoice]=useState(apartments[0].name); const [compare,setCompare]=useState(apartments[9].name);
  const choices=useMemo(()=>['전체 아파트',...apartments.filter(a=>dong==='전체'||a.dong===dong).map(a=>a.name)],[dong]);
  const visible=useMemo(()=>apartments.filter(a=>dong==='전체'||a.dong===dong).map((a,i)=>({...a,rank:i+1,count:Math.max(4,Math.round(a.count*(period==='일간'?.12:period==='주간'?.43:1)*(deal==='매매'?1:deal==='전세'?.82:.68)))})).slice(0,10),[dong,period,deal]);
  const volume=useMemo(()=>{const factor=apartment==='전체 아파트'?(dong==='전체'?1:.42):.12;return volumeBase.map(v=>({...v,sale:Math.max(1,Math.round(v.sale*factor)),jeonse:Math.max(1,Math.round(v.jeonse*factor)),rent:Math.max(1,Math.round(v.rent*factor))}))},[dong,apartment]);
  const selectedCompare=apartments.find(a=>a.name===compare)??apartments[9];
  return <main className="min-h-screen bg-background text-foreground"><div className="mx-auto max-w-[1480px] px-4 pb-16 pt-6 sm:px-6 lg:px-9">
    <header className="mb-7 flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between"><div className="flex items-center gap-3.5"><div className="grid size-11 place-items-center rounded-2xl bg-primary text-primary-foreground shadow-[0_10px_28px_rgba(37,99,235,.22)]"><Building2 className="size-5"/></div><div><div className="flex items-center gap-2"><h1 className="text-[19px] font-bold tracking-[-.035em]">화성 부동산 인사이트</h1><span className="rounded-full bg-blue-100 px-2 py-.5 text-[10px] font-bold text-blue-700">BRIEFING</span></div><p className="mt-.5 text-xs text-muted-foreground">고객의 결정을 빠르게 만드는 아파트 시장 브리핑</p></div></div>
      <div className="flex flex-wrap items-center gap-2 rounded-2xl border bg-white/80 p-2 shadow-[0_14px_50px_rgba(70,102,140,.08)] backdrop-blur"><Select value={dong} onValueChange={v=>{setDong(v as string);setApartment('전체 아파트')}}><SelectTrigger className="h-10 min-w-[145px] border-0 bg-secondary px-3.5 font-semibold"><MapPin className="size-4 text-primary"/><SelectValue/></SelectTrigger><SelectContent>{dongs.map(d=><SelectItem key={d} value={d}>{d==='전체'?'화성시 전체':d}</SelectItem>)}</SelectContent></Select><Select value={apartment} onValueChange={v=>setApartment(v as string)}><SelectTrigger className="h-10 min-w-[220px] border-0 bg-secondary px-3.5 font-semibold"><Building2 className="size-4 text-primary"/><SelectValue/></SelectTrigger><SelectContent>{choices.map(a=><SelectItem key={a} value={a}>{a}</SelectItem>)}</SelectContent></Select><button onClick={()=>document.getElementById('comparison')?.scrollIntoView({behavior:'smooth'})} className="inline-flex h-10 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-bold text-white transition hover:-translate-y-.5 hover:shadow-lg"><Sparkles className="size-4"/> 고객 브리핑 시작</button></div></header>

    <section className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['이번 달 총 거래','1,248건','전월 대비 8.4%'],['평균 매매가','6억 8,420만','전월 대비 2.1%'],['평균 전세가율','63.8%','안정 구간'],['가장 활발한 지역','동탄6동','186건 거래']].map(([l,v,n],i)=><article key={l} className="rounded-[22px] border border-white/80 bg-card p-5 shadow-[0_14px_40px_rgba(56,86,125,.07)] transition hover:-translate-y-1"><div className="mb-3 flex items-center justify-between text-xs font-medium text-muted-foreground"><span>{l}</span><span className="grid size-8 place-items-center rounded-xl bg-blue-50 text-primary">{i===3?<MapPin className="size-4"/>:<TrendingUp className="size-4"/>}</span></div><strong className="text-2xl tracking-[-.045em]">{v}</strong><p className={`mt-2 text-xs font-semibold ${i<2?'text-emerald-600':'text-muted-foreground'}`}>{n}</p></article>)}</section>

    <section className="panel mb-5 overflow-hidden"><div className="flex flex-col gap-4 border-b px-5 py-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-1 flex items-center gap-2"><i className="size-2 rounded-full bg-primary"/><h2 className="font-bold">아파트 거래 TOP 10</h2></div><p className="text-xs text-muted-foreground">선택 기간 내 실거래 신고 건수 기준</p></div><div className="flex flex-wrap items-center gap-2"><Segment items={['매매','전세','월세']} value={deal} setValue={setDeal}/><Segment items={['일간','주간','월간']} value={period} setValue={setPeriod}/><label className="date-field"><CalendarDays className="size-4 text-primary"/><span className="sr-only">시작일</span><input type="date" value={start} onChange={e=>setStart(e.target.value)}/><span className="text-slate-300">—</span><span className="sr-only">종료일</span><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div></div>
      <div className="overflow-x-auto px-3 pb-3"><table className="w-full min-w-[780px] border-separate border-spacing-y-1.5 text-left"><thead className="text-[11px] font-bold text-muted-foreground"><tr><th className="px-4 py-2">순위</th><th>아파트</th><th>법정동</th><th>거래건수</th><th>최근 {deal}가</th><th>가격 흐름</th><th/></tr></thead><tbody>{visible.map(a=><tr key={a.name} className="bg-slate-50/70 text-sm transition hover:bg-blue-50/80"><td className="rounded-l-xl px-4 py-2.5"><span className={`grid size-7 place-items-center rounded-lg text-xs font-extrabold ${a.rank<4?'bg-primary text-white':'bg-white text-slate-500'}`}>{a.rank}</span></td><td className="font-bold text-slate-800">{a.name}</td><td className="text-slate-500">{a.dong}</td><td><strong>{a.count}</strong><small className="ml-1 text-slate-400">건</small></td><td className="font-semibold">{priceText(deal,a)}</td><td><span className="rounded-lg bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-600">{a.change}</span></td><td className="rounded-r-xl pr-3 text-right"><button onClick={()=>{setTopChoice(a.name);document.getElementById('comparison')?.scrollIntoView({behavior:'smooth'})}} aria-label={`${a.name} 비교하기`} className="rounded-lg p-2 text-slate-400 hover:bg-white hover:text-primary"><ChevronRight className="size-4"/></button></td></tr>)}</tbody></table></div></section>

    <section className="panel mb-5 grid gap-0 overflow-hidden lg:grid-cols-[1fr_280px]"><div className="p-5 sm:p-6"><div className="mb-5 flex items-start justify-between"><div><h2 className="font-bold">거래 유형별 건수</h2><p className="mt-1 text-xs text-muted-foreground">{dong==='전체'?'화성시 전체':dong} · {apartment}</p></div><span className="pill">최근 7일</span></div><ChartContainer config={{sale:{label:'매매',color:'#2f6fed'},jeonse:{label:'전세',color:'#65a2ff'},rent:{label:'월세',color:'#9cc6ff'}}} className="h-[285px] w-full"><BarChart data={volume} margin={{left:-18,right:4}}><CartesianGrid vertical={false} strokeDasharray="4 4"/><XAxis dataKey="day" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><ChartTooltip content={<ChartTooltipContent/>}/><Bar dataKey="sale" stackId="a" fill="var(--color-sale)" radius={[0,0,4,4]}/><Bar dataKey="jeonse" stackId="a" fill="var(--color-jeonse)"/><Bar dataKey="rent" stackId="a" fill="var(--color-rent)" radius={[4,4,0,0]}/></BarChart></ChartContainer></div><aside className="border-t bg-slate-50/65 p-6 lg:border-l lg:border-t-0"><p className="text-xs font-bold text-muted-foreground">한눈에 보는 수요</p><strong className="mt-2 block text-3xl tracking-[-.05em]">{volume.reduce((s,v)=>s+v.sale+v.jeonse+v.rent,0)}건</strong><p className="mt-1 text-xs text-emerald-600">직전 7일 대비 +12.6%</p><div className="mt-8 space-y-5">{[['매매','#2f6fed','48%'],['전세','#65a2ff','31%'],['월세','#9cc6ff','21%']].map(([l,c,p])=><div key={l}><div className="mb-2 flex justify-between text-xs"><span className="font-semibold">{l}</span><b>{p}</b></div><div className="h-2 rounded-full bg-slate-200"><div className="h-full rounded-full" style={{width:p,background:c}}/></div></div>)}</div></aside></section>

    <section id="comparison" className="panel mb-5 p-5 sm:p-6"><div className="mb-6 flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><span className="eyebrow">APARTMENT COMPARISON</span><h2 className="mt-2 text-xl font-bold tracking-[-.035em]">인기 단지와 관심 단지를 나란히 비교</h2><p className="mt-1 text-sm text-muted-foreground">가격 흐름과 거래 경쟁력을 고객에게 쉽게 설명하세요.</p></div><div className="flex flex-col items-stretch gap-2 sm:flex-row sm:items-center"><CompareSelect label="TOP 단지" value={topChoice} onChange={setTopChoice}/><span className="hidden text-xs font-black text-slate-300 sm:block">VS</span><CompareSelect label="관심 단지" value={compare} onChange={setCompare}/></div></div>
      <div className="grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><div className="rounded-2xl border bg-slate-50/55 p-4"><div className="mb-2 flex flex-wrap gap-4 text-xs"><span><i className="mr-2 inline-block size-2 rounded-full bg-blue-600"/>{topChoice}</span><span><i className="mr-2 inline-block size-2 rounded-full bg-emerald-400"/>{compare}</span></div><ResponsiveContainer width="100%" height={290}><AreaChart data={trend}><defs><linearGradient id="topFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2f6fed" stopOpacity=".22"/><stop offset="1" stopColor="#2f6fed" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#dfe8f2" strokeDasharray="4 4"/><XAxis dataKey="month" tickLine={false} axisLine={false} fontSize={11}/><YAxis domain={[6,16]} tickLine={false} axisLine={false} fontSize={11} unit="억"/><Tooltip formatter={(v)=>`${v}억`}/><Area type="monotone" dataKey="top" stroke="#2f6fed" strokeWidth={3} fill="url(#topFill)"/><Line type="monotone" dataKey="mine" stroke="#51bfa8" strokeWidth={3} dot={{r:3}}/></AreaChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-3">{[['최근 매매가',`${apartments.find(a=>a.name===topChoice)?.sale??14.8}억`,`${selectedCompare.sale}억`],['6개월 상승률','+10.4%','+5.3%'],['최근 거래량','28건',`${selectedCompare.count}건`],['전세가율','50.0%',`${Math.round(selectedCompare.jeonse/selectedCompare.sale*100)}%`]].map(([l,a,b])=><div key={l} className="rounded-2xl border bg-white p-4"><p className="text-xs font-semibold text-muted-foreground">{l}</p><div className="mt-3 flex items-end justify-between gap-2"><div><small className="block text-[10px] text-blue-600">TOP</small><b className="text-lg">{a}</b></div><div className="text-right"><small className="block text-[10px] text-emerald-600">관심</small><b className="text-lg">{b}</b></div></div></div>)}</div></div>
    </section>

    <section className="panel overflow-hidden"><div className="grid xl:grid-cols-[.9fr_1.5fr]"><div className="bg-gradient-to-br from-[#245fd2] to-[#4892f1] p-6 text-white sm:p-8"><span className="text-[10px] font-bold tracking-[.15em] text-blue-100">LOCATION REPORT</span><h2 className="mt-3 text-2xl font-bold tracking-[-.04em]">{compare}</h2><p className="mt-2 text-sm text-blue-100">생활권을 숫자로 설명하는 입지 브리핑</p><div className="mt-8 grid grid-cols-3 gap-2"><Score label="교통" value="94"/><Score label="교육" value="88"/><Score label="생활" value="91"/></div><div className="mt-8 rounded-2xl bg-white/12 p-4 backdrop-blur"><p className="text-xs font-bold text-blue-100">고객 브리핑 한 문장</p><p className="mt-2 text-sm leading-6">“동탄역을 도보로 이용하면서 공원과 상권까지 가까운, 실거주 선호도가 높은 생활권입니다.”</p></div></div><div className="p-5 sm:p-7"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-bold">핵심 입지 거리</h3><p className="mt-1 text-xs text-muted-foreground">단지 출입구 기준 예상 거리</p></div><span className="pill"><MapPin className="size-3"/> 반경 5.5km</span></div><div className="grid gap-3 sm:grid-cols-2">{locationItems.map(item=><div key={item.label} className="flex items-center gap-3 rounded-2xl border bg-slate-50/55 p-3.5"><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${item.color}`}><item.icon className="size-4.5"/></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{item.label}</p><p className="mt-1 text-[11px] text-muted-foreground">{item.note}</p></div><div className="text-right"><b className="whitespace-nowrap text-sm text-primary">{item.distance}</b><div className="mt-1 h-1 w-10 rounded-full bg-slate-200"><div className="h-full rounded-full bg-primary" style={{width:`${item.score}%`}}/></div></div></div>)}</div><div className="mt-5 rounded-2xl border border-blue-100 bg-blue-50/70 p-4"><div className="flex items-start gap-3"><Sparkles className="mt-.5 size-5 shrink-0 text-primary"/><div><p className="text-sm font-bold text-blue-950">중개 포인트</p><p className="mt-1 text-xs leading-5 text-blue-800">역세권·공원·중심상권이 모두 도보권입니다. 삼성전자 출퇴근 수요와 GTX-A 광역 교통 수요를 함께 설명하면 단지의 가격 방어력을 설득하기 좋습니다.</p></div></div></div></div></div></section>
    <footer className="mt-4 flex flex-col justify-between gap-2 text-[11px] text-muted-foreground sm:flex-row"><p>데모 데이터 · 실제 고객 브리핑 전 국토교통부 실거래가 및 거리 API 연동 필요</p><p>조회 기준 {start} — {end}</p></footer>
  </div></main>
}

function Segment({items,value,setValue}:{items:string[];value:string;setValue:(v:string)=>void}){return <div className="flex rounded-xl bg-secondary p-1">{items.map(i=><button key={i} onClick={()=>setValue(i)} className={`rounded-lg px-3.5 py-2 text-xs font-bold transition ${value===i?'bg-white text-primary shadow-sm':'text-muted-foreground hover:text-foreground'}`}>{i}</button>)}</div>}
function CompareSelect({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="rounded-xl border bg-white px-3 py-2"><span className="mb-1 block text-[9px] font-bold tracking-wider text-muted-foreground">{label}</span><Select value={value} onValueChange={v=>onChange(v as string)}><SelectTrigger className="h-6 min-w-[210px] border-0 p-0 font-bold shadow-none"><SelectValue/></SelectTrigger><SelectContent>{apartments.map(a=><SelectItem key={a.name} value={a.name}>{a.name}</SelectItem>)}</SelectContent></Select></label>}
function Score({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-white/12 px-3 py-3 text-center"><strong className="text-xl">{value}</strong><span className="block text-[10px] text-blue-100">{label}</span></div>}
